---
book_repo: dingodb/docs-book
cred_repo: dingodb/docs-site-credentials
layout_repo: pivotal-cf/docs-layout-repo

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: false
feedback_enabled: false

sections:
- repository:
    name: dingodb/docs-dingo-s3
  directory: dingo-s3
  subnav_template: dingo_s3_subnav.erb


template_variables:
  title: Dingo Tiles
  book_title: Dingo Tiles
  hero_text: Amplify and extend Pivotal Cloud Foundry to make all your developers and admins crazy happy
  book_title_short: Dingo Tiles
  # title: Dingo Tiles Documentation
  # book_title: Dingo Tiles Documentation
  # hero_text: Learn how to use Dingo Tiles to make your developers go fast
  # book_title_short: Dingo Docs

  support_url: https://slack.dingotiles.com

  domain_name: docs.dingotiles.com


  product_link:
  support_link: <a href="https://slack.dingotiles.com" target="_blank">Ask any question anytime on Slack</a>
  support_call_to_action: <script async defer src="https://slack.dingotiles.com/slackin.js"></script>

  # https://cse.google.com/cse/
  cse_id: configyml.cse_id
  ga_account_id: configyml.ga_account_id

public_host: docs.dingotiles.com
